#ifndef CUDA_THREAD_MANAGEMENT_CUH
#define CUDA_THREAD_MANAGEMENT_CUH

#include <inttypes.h>
#include <cuda_runtime.h>
#include <device_launch_parameters.h>
#include "../ceilDiv.h"


#define THREAD_LOCAL_X_ID (threadIdx.x)
#define THREAD_LOCAL_Y_ID (threadIdx.y)
#define THREAD_LOCAL_Z_ID (threadIdx.z)

#define BLOCK_X_ID (blockIdx.x)
#define BLOCK_Y_ID (blockIdx.y)
#define BLOCK_Z_ID (blockIdx.z)

#define BLOCK_X_SIZE (blockDim.x)
#define BLOCK_Y_SIZE (blockDim.y)
#define BLOCK_Z_SIZE (blockDim.z)


#define BLOCK_SIZE_1D (BLOCK_X_SIZE)
#define BLOCK_SIZE_2D (BLOCK_X_SIZE * BLOCK_Y_SIZE)
#define BLOCK_SIZE_3D (BLOCK_X_SIZE * BLOCK_Y_SIZE * BLOCK_Z_SIZE)

#define GLOBAL_THREAD_X_SIZE (BLOCK_X_SIZE * gridDim.x)
#define GLOBAL_THREAD_Y_SIZE (BLOCK_Y_SIZE * gridDim.y)
#define GLOBAL_THREAD_Z_SIZE (BLOCK_Z_SIZE * gridDim.z)


#define THREAD_GLOBAL_X_ID (THREAD_LOCAL_X_ID + BLOCK_X_ID * BLOCK_X_SIZE)
#define THREAD_GLOBAL_Y_ID (THREAD_LOCAL_Y_ID + BLOCK_Y_ID * BLOCK_Y_SIZE)
#define THREAD_GLOBAL_Z_ID (THREAD_LOCAL_Z_ID + BLOCK_Z_ID * BLOCK_Z_SIZE)


#define THREAD_LOCAL_ID_1D (THREAD_LOCAL_X_ID)
#define THREAD_LOCAL_ID_2D (THREAD_LOCAL_X_ID + THREAD_LOCAL_Y_ID * BLOCK_X_SIZE)
#define THREAD_LOCAL_ID_3D (THREAD_LOCAL_X_ID + THREAD_LOCAL_Y_ID * BLOCK_X_SIZE + THREAD_LOCAL_Z_ID * (BLOCK_X_SIZE * BLOCK_Y_SIZE))

#define BLOCK_ID_1D (BLOCK_X_ID)
#define BLOCK_ID_2D (BLOCK_X_ID + BLOCK_Y_ID * BLOCK_X_SIZE)
#define BLOCK_ID_3D (BLOCK_X_ID + BLOCK_Y_ID * BLOCK_X_SIZE + BLOCK_Z_ID * BLOCK_X_SIZE * BLOCK_Y_SIZE)


#define THREAD_GLOBAL_BLOCK_FILL_ID_1D (THREAD_LOCAL_ID_1D + BLOCK_ID_1D * BLOCK_SIZE_1D)
#define THREAD_GLOBAL_BLOCK_FILL_ID_2D (THREAD_LOCAL_ID_2D + BLOCK_ID_2D * BLOCK_SIZE_2D)
#define THREAD_GLOBAL_BLOCK_FILL_ID_3D (THREAD_LOCAL_ID_3D + BLOCK_ID_3D * BLOCK_SIZE_3D)

#define THREAD_GLOBAL_BLOCK_SKIP_ID_1D (THREAD_GLOBAL_X_ID)
#define THREAD_GLOBAL_BLOCK_SKIP_ID_2D (THREAD_GLOBAL_X_ID + THREAD_GLOBAL_Y_ID * GLOBAL_THREAD_X_SIZE)
#define THREAD_GLOBAL_BLOCK_SKIP_ID_3D (THREAD_GLOBAL_X_ID + THREAD_GLOBAL_Y_ID * GLOBAL_THREAD_X_SIZE + THREAD_GLOBAL_Z_ID * GLOBAL_THREAD_X_SIZE * GLOBAL_THREAD_Y_SIZE)

// cuThreadManagement.cuh

#endif // CUDA_THREAD_MANAGEMENT_CUH //